export const ADD = "ADD";

export const SUBTRACT = "SUBTRACT";

export const MULTIPLY = "MULTIPLY";

export const DIVIDE = "DIVIDE";

export const ADD_WITH_RANDOM = "ADD_WITH_RANDOM";

export const ADD_WITH_RANDOM_SUCCESS = "ADD_WITH_RANDOM_SUCCESS";

export const ADD_WITH_RANDOM_FAILURE = "ADD_WITH_RANDOM_FAILURE";

export const MULTIPLY_WITH_RANDOM = "MULTIPLY_WITH_RANDOM";

export const MULTIPLY_WITH_RANDOM_SUCCESS = "MULTIPLY_WITH_RANDOM_SUCCESS";

export const MULTIPLY_WITH_RANDOM_FAILURE = "MULTIPLY_WITH_RANDOM_FAILURE";
